# Generated by Django 4.1 on 2026-06-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/'),
        ),
    ]
