# Generated by Django 4.1 on 2026-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="status",
            field=models.TextField(
                choices=[
                    ("OPEN", "Открыто"),
                    ("CLOSED", "Закрыто"),
                    ("DRAFT", "Черновик"),
                ],
                default="OPEN",
            ),
        ),
    ]
